### PR TITLE
Add defmt attributes for caches

### PR DESCRIPTION
**Pull request by liamkinne**

### CODE REVIEW

**Comment by diondokter** [comment]
Hi, thanks!

If you add a line to the changelog, then I'll merge this and make a release

**Comment by liamkinne** [comment]
Done

**Comment by diondokter** [comment]
It doesn't pass CI yet. Try building the crate with `cargo build --features defmt-03`. You'll see there's an error

**Comment by liamkinne** [comment]
Strange, the error only shows up when building from the example crate. Fixed now.

**Comment by diondokter** [comment]
> Strange, the error only shows up when building from the example crate. Fixed now.

The normal CI doesn't build with defmt, so that's why. The example does use it, so it breaks there.

**Comment by diondokter** [comment]
Thanks!

**Comment by diondokter** [comment]
And now also released as 3.0.1

**Pull request merged**
